apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snap-it-server
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
spec:
  project: default
  source:
    repoURL: https://github.com/chabinhwang/snap-it-k8s-manifest  # snap-it-manifests-structure.md에 언급된 저장소
    path: snap-it-manifests/snap-it-chart  # 매니페스트 구조 문서에 언급된 경로
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: snapit  # values.yaml에 정의된 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 