# Snap-It Server 애플리케이션을 위한 기본 값 설정
replicaCount: 1

namespace: snapit

image:
  repository: ghcr.io/chabinhwang/snap-it-server
  tag: 9de9e8db82683c4072555a177bce26ffb7ec36d5
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: my-registry-secret

service:
  type: NodePort
  port: 8080
  nodePort: 32766


# 리소스 제한
# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 200m
#     memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false 

secrets:
  name: my-secret