apiVersion: apps/v1
kind: Deployment
metadata:
  name: snap-it-server
  namespace: {{ .Values.namespace }}
  labels:
    app: snap-it-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: snap-it-server
  template:
    metadata:
      labels:
        app: snap-it-server
    spec:
      containers:
        - name: snap-it-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name }}